### ISSUE TITLE
Since 5 hours the library crashes with JSONDecodeError trying to parse "Unknown location; please try <coordinate>" as JSON

### ISSUE THREAD

**Issue by hnsl** [chubin/wttr.in#1028]
```
Traceback (most recent call last):
  File "/home/hnsl/.local/lib/python3.12/site-packages/python_weather/client.py", line 123, in get
    return Forecast(await resp.json(), unit, locale)
                    ^^^^^^^^^^^^^^^^^
  File "/home/hnsl/.local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1294, in json
    return loads(stripped.decode(encoding))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

The API doesn't support named locations anymore?

**Comment by hnsl** [comment]
API seems down: 

https://wttr.in/Stockholm?format=j1

Unknown location; please try ~59.3251172,18.0710935

**Comment by hnsl** [comment]
I switched to using SHMI data source directly since wttr.in seems unreliable: https://opendata.smhi.se/apidocs

If if's provides global weather you could consider using that as a data source instead.

**Comment by chubin** [comment]
It should be better now. Sorry for the inconvenience.
