### ISSUE TITLE
Error with :help page

### ISSUE THREAD

**Issue by ogarcia** [chubin/wttr.in#134]
After a clan install, when you request for `:help` page you have the following error:

```
ERROR:__main__:Exception on /:help [GET]
Traceback (most recent call last):
  File "/srv/webservices/wttr/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/webservices/wttr/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/webservices/wttr/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/webservices/wttr/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/webservices/wttr/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/webservices/wttr/wttr.in/bin/srv.py", line 240, in wttr
    return render_template( 'index.html', body=help_ )
  File "/srv/webservices/wttr/venv/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/srv/webservices/wttr/venv/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/srv/webservices/wttr/venv/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/srv/webservices/wttr/venv/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/webservices/wttr/home/share/templates/index.html", line 7, in top-level template code
    {{ body }}
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 230: ordinal not in range(128)
```

**Comment by chubin** [comment]
It's not (yet) complete synchronized with the code on the server. There is an issue about it.
Do you want to install it locally?

**Comment by ogarcia** [comment]
@chubin Yes, I have a small own local server

**Comment by chubin** [comment]
The code is synchronized now.
