### ISSUE TITLE
Cannot import name v3 from view

### ISSUE THREAD

**Issue by jonas-w** [chubin/wttr.in#751]
Okay i followed your documentation to install it.
Everything seems set up.
I have all the requirements and the maxminddb.
> But now if i want to start `python3 bin/srv.py` this error pops up:

```
/home/jonas/wttr.in/wttr_venvc/lib/python3.9/site-packages/numpy/core/getlimits.py:499: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/jonas/wttr.in/wttr_venvc/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/home/jonas/wttr.in/wttr_venvc/lib/python3.9/site-packages/numpy/core/getlimits.py:499: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/jonas/wttr.in/wttr_venvc/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
Traceback (most recent call last):
  File "/home/jonas/wttr.in/bin/srv.py", line 20, in <module>
    import wttr_srv
  File "/home/jonas/wttr.in/lib/wttr_srv.py", line 30, in <module>
    from view.line import wttr_line
  File "/home/jonas/wttr.in/lib/view/line.py", line 31, in <module>
    from . import v3
ImportError: cannot import name 'v3' from 'view' (/home/jonas/wttr.in/lib/view/__init__.py)
```

**Comment by chubin** [comment]
Yes, you are right. The v3 source code is not yet in the source tree. There is only a wrapper here, which gets the data generated by the v3.wttr.in service. The code should be merged in the main source tree. That's good that you reminded me about it.

**Comment by TheTomahawk** [comment]
It's still not there...

https://github.com/chubin/wttr.in/blob/575908ae51010b2d71c0b1d4bf4def997bea0fa3/lib/view/line.py#L31
https://github.com/chubin/wttr.in/tree/master/lib
